.\" Copyright (c) 2011-2014 Marc-Antoine Perennou <Marc-Antoine@Perennou.com>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
.\" Boston, MA  02111-1301  USA.
.TH GPASTE 1
.SH NAME
GPaste \- A lightweight clipboard manager for the Gnome desktop

.SH "SYNOPSIS"
.B [command |] gpaste [options...]

.SH "DESCRIPTION"
GPaste is a modular clipboard management system with a fully
DBus-based daemon, a \s-1CLI\s0 client and a gtk+ tray icon.

.SH "COMMANDS"

.TP
.B gpaste [history]
Display the history with indexes
.br
.TP
.B gpaste history-size
Display this size of the history
.br
.TP
.B gpaste backup-history
Backup the current history
.br
.TP
.B gpaste switch-history
Switch to another history
.br
.TP
.B gpaste delete-history
Delete a history
.br
.TP
.B gpaste list-histories
List available histories
.br
.TP
.B gpaste add <text>
Add the text into the history
.br
.TP
.B gpaste add-password <name> <password>
Add the name - password couple to the history
.br
.TP
.B gpaste delete-password <name>
Delete the password <name>
.br
.TP
.B gpaste set-password <number> <name>
Mark the <number>th item of the history as being a password named <name>
.br
.TP
.B gpaste rename-password <old name> <new name>
Rename the password
.br
.TP
.B gpaste get <number>
Get the <number>th item from the history
.br
.TP
.B gpaste select <number>
Put the <number>th item of the history into the clipboard
.br
.TP
.B gpaste delete <number>
Delete the <number>th item of the history
.br
.TP
.B gpaste file <path>
Put the content of the file at <path> into the clipboard
.br
.TP
.B command | gpaste
Put the output of the command into the history
.br
.TP
.B gpaste empty
Empty the history
.br
.TP
.B gpaste start
Start tracking clipboard changes
.br
.TP
.B gpaste stop
Stop tracking clipboard changes
.br
.TP
.B gpaste daemon-reexec
Reexecute the daemon, for example after upgrading GPaste
.br
.TP
.B gpaste settings
Launch the configuration tool
.br
.TP
.B gpaste version
Display the version
.br
.TP
.B gpaste daemon-version
Display the daemon version
.br
.TP
.B gpaste help
Display the help
.br
.TP
.B gpaste about
Display the about dialog
.br
.TP
.B gpaste show-history
Make the applet or extension display the history
.br

.SH "OPTIONS"

.TP
.B --oneline
Display each item on one line, without new lines
.br
.TP
.B --raw
Display the item raw (without index)
.br
.TP
.B --zero
Use NUL character instead of new lines between each item
.br
