.\" This file is part of GPaste.
.\"
.\" Copyright (c) 2010-2018, Marc-Antoine Perennou <Marc-Antoine@Perennou.com>
.TH GPASTE-CLIENT 1
.SH NAME
GPaste \- A lightweight clipboard manager for the Gnome desktop

.SH "SYNOPSIS"
.B [command |] gpaste-client [options...]

.SH "DESCRIPTION"
GPaste is a modular clipboard management system with a fully
DBus-based daemon, a \s-1CLI\s0 client and a gtk+ tray icon.

.SH "COMMANDS"

.TP
.B gpaste-client [history]
Display the history with indexes
.br
.TP
.B gpaste-client history-size
Display this size of the history
.br
.TP
.B gpaste-client get-history
Get the name of the current history
.br
.TP
.B gpaste-client backup-history
Backup the current history
.br
.TP
.B gpaste-client switch-history
Switch to another history
.br
.TP
.B gpaste-client delete-history
Delete a history
.br
.TP
.B gpaste-client list-histories
List available histories
.br
.TP
.B gpaste-client add <text>
Add the text into the history
.br
.TP
.B gpaste-client add-password <name> <password>
Add the name \- password couple to the history
.br
.TP
.B gpaste-client delete-password <name>
Delete the password <name>
.br
.TP
.B gpaste-client set-password <uuid> <name>
Mark the item matching <uuid> from the history as being a password named <name>
.br
.TP
.B gpaste-client rename-password <old name> <new name>
Rename the password
.br
.TP
.B gpaste-client get <uuid>
Get the item matching <uuid> from the history
.br
.TP
.B gpaste-client select <uuid>
Put the item matching <uuid> from the history into the clipboard
.br
.TP
.B gpaste-client replace <uuid> <contents>
Replace the contents of the item matching <uuid> from the history with the provided one
.br
.TP
.B gpaste-client merge [--decoration|-d <string>] [--separator|-s <string>] <uuid> … <uuid>
Merge the items matching the uuids from the history and put the result in the clipboard
.br
If foo bar and baz are respectively uuids 5cb227f9-857d-490b-8ea1-f5f33f59f04e b4a7aa02-ef9a-4c29-b951-ebbdb4ed279b and
99da883b-0544-4cb4-92dd-733420a9db6d in history and you run
.br
gpaste-client merge \-d '"' \-s ',' 5cb227f9-857d-490b-8ea1-f5f33f59f04e b4a7aa02-ef9a-4c29-b951-ebbdb4ed279b
99da883b-0544-4cb4-92dd-733420a9db6d
.br
You will end up with "foo","bar","baz" in your clipboard
.br
.TP
.B gpaste-client delete <uuid>
Delete the item matching <uuid> from the history
.br
.TP
.B gpaste-client file <path>
Put the content of the file at <path> into the clipboard
.br
.TP
.B command | gpaste-client
Put the output of the command into the history
.br
.TP
.B gpaste-client empty
Empty the history
.br
.TP
.B gpaste-client start
Start tracking clipboard changes
.br
.TP
.B gpaste-client stop
Stop tracking clipboard changes
.br
.TP
.B gpaste-client upload <uuid>
Upload the item matching <uuid> to a pastebin service
.br
.TP
.B gpaste-client ui
Launch the graphical tool
.br
.TP
.B gpaste-client daemon-reexec
Reexecute the daemon, for example after upgrading GPaste
.br
.TP
.B gpaste-client settings
Launch the configuration tool
.br
.TP
.B gpaste-client version
Display the version
.br
.TP
.B gpaste-client daemon-version
Display the daemon version
.br
.TP
.B gpaste-client help
Display the help
.br
.TP
.B gpaste-client about
Display the about dialog
.br
.TP
.B gpaste-client show-history
Make the applet or extension display the history
.br

.SH "OPTIONS"

.TP
.B --use-index
Use the item index instead of its uuid
.br
.TP
.B --oneline
Display each item on one line, without new lines
.br
.TP
.B --raw
Display the item raw (without index)
.br
.TP
.B --reverse
Display the items in reverse order
.br
.TP
.B --zero
Use NUL character instead of new lines between each item
.br
